---
version: 5

defaults:
  datadir: /etc/puppetlabs
  data_hash: yaml_data

hierarchy:
  - name: "Nodes"
    path: "nodes/%{trusted.certname}.yaml"

  - name: "environment defaults"
    path: "environment.yaml"

  - name: "Common defaults"
    path: "common.yaml"