#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# modules from the Puppet Forge
mod 'biemond/jdk7'
mod 'biemond/orautils'
mod 'biemond/orawls'
mod 'adrien/filemapper'
mod 'reidmv/yamlfile'
mod 'hajee/easy_type'
mod 'fiddyspence/sleep'
mod 'puppetlabs/stdlib'
