---

logoutput:                      &logoutput                true
orawls::weblogic::log_output:   *logoutput

# global WebLogic vars
wls_oracle_base_home_dir: &wls_oracle_base_home_dir "/opt/oracle"
wls_weblogic_user:        &wls_weblogic_user        "weblogic"
wls_weblogic_home_dir:    &wls_weblogic_home_dir    "/opt/oracle/middleware12c/wlserver"
wls_middleware_home_dir:  &wls_middleware_home_dir  "/opt/oracle/middleware12c"
wls_version:              &wls_version              12212

# global OS vars
wls_os_user:              &wls_os_user              "oracle"
wls_os_group:             &wls_os_group             "dba"
wls_download_dir:         &wls_download_dir         "/var/tmp/install"
wls_source:               &wls_source               "/var/tmp/install"
wls_jdk_home_dir:         &wls_jdk_home_dir         "/usr/java/latest"
wls_log_dir:              &wls_log_dir              "/var/log/weblogic"

wls_domains_dir:          &wls_domains_dir          '/opt/oracle/wlsdomains/domains'
wls_apps_dir:             &wls_apps_dir             '/opt/oracle/wlsdomains/applications'

wls_jsse_enabled:         &wls_jsse_enabled         true



#WebLogic installation variables
orawls::weblogic::version:                   *wls_version
orawls::weblogic::filename:                  'fmw_12.2.1.2.0_wls.jar'
orawls::weblogic::log_output:                true
orawls::weblogic::jdk_home_dir:              *wls_jdk_home_dir
orawls::weblogic::oracle_base_home_dir:      *wls_oracle_base_home_dir
orawls::weblogic::puppet_download_mnt_point: *wls_source
orawls::weblogic::remote_file:               false
orawls::weblogic::wls_domains_dir:           *wls_domains_dir
orawls::weblogic::wls_apps_dir:              *wls_apps_dir
orawls::weblogic::middleware_home_dir:       *wls_middleware_home_dir
orawls::weblogic::weblogic_home_dir:         *wls_weblogic_home_dir






#fmw_installations:

#opatch_instances:


# handy WebLogic scripts in /opt/scripts/wls
orautils::os_oracle_home:      *wls_oracle_base_home_dir
orautils::ora_inventory:       "/opt/oracle/oraInventory"
orautils::os_domain_type:      "admin"
orautils::os_log_folder:       *wls_log_dir
orautils::os_download_folder:  *wls_download_dir
orautils::os_mdw_home:         *wls_middleware_home_dir
orautils::os_wl_home:          *wls_weblogic_home_dir
orautils::ora_user:            *wls_os_user
orautils::ora_group:           *wls_os_group

orautils::node_mgr_port:       5556

orautils::wls_user:           *wls_weblogic_user
orautils::jsse_enabled:       true


# when you have just one domain on a server
domain_name:                &domain_name                "Wls1221"
domain_adminserver:         &domain_adminserver         "AdminServer"
domain_adminserver_address: &domain_adminserver_address "127.0.0.1"
domain_adminserver_port:    &domain_adminserver_port    7001
domain_nodemanager_port:    &domain_nodemanager_port    5556
domain_wls_password:        &domain_wls_password        "weblogic1"
domain_user_config_file:    "/home/oracle/oracle-Wls1221-WebLogicConfig.properties"
domain_user_key_file:       "/home/oracle/oracle-Wls1221-WebLogicKey.properties"

orautils::os_domain:           *domain_name
orautils::os_domain_path:      "/opt/oracle/wlsdomains/domains/Wls1221"
orautils::node_mgr_path:       "/opt/oracle/wlsdomains/domains/Wls1221/bin"
orautils::node_mgr_address:    *domain_adminserver_address
orautils::wls_password:        *domain_wls_password
orautils::wls_adminserver:     *domain_adminserver

# create a standard domain with custom identity for the adminserver
domain_instances:
  'Wls1221':
    domain_template:                       "standard"
    development_mode:                      true
    domain_name:                           *domain_name
    adminserver_listen_on_all_interfaces:  true
    adminserver_ssl_port:                  7002
    weblogic_password:                     *domain_wls_password
    jsse_enabled:                          *wls_jsse_enabled
    log_dir:                               *wls_log_dir


wls_setting_instances:
  'default':
    user:               *wls_os_user
    weblogic_home_dir:  *wls_weblogic_home_dir
    connect_url:        "t3://127.0.0.1:7001"
    weblogic_user:      *wls_weblogic_user
    weblogic_password:  *domain_wls_password
    require:            Orawls::Domain[Wls1221]

# pack domains
pack_domain_instances:
  'wlsDomain':
    log_output:           *logoutput

# create and startup the nodemanager
nodemanager_instances:
  'nodemanager':
    log_output:                            *logoutput
    nodemanager_address:                   *domain_adminserver_address
    log_file:                              'nodemanager_plain.log'
    nodemanager_port:                      5556
    domain_name:                           *domain_name
    custom_trust:                          false
    custom_identity:                       false
    sleep:                                 20
    jsse_enabled:                          *wls_jsse_enabled


# startup adminserver for extra configuration
control_instances:
  'startWLSAdminServer':
     domain_name:                 *domain_name
     server_type:                 'admin'
     target:                      'Server'
     action:                      'start'
     jsse_enabled:                *wls_jsse_enabled
     adminserver_address:         *domain_adminserver_address
     weblogic_password:           *domain_wls_password                 


# create password file for WLST utility
userconfig_instances:
  'Wls12c':
    user_config_dir:      '/home/oracle'
    domain_name:          *domain_name
    adminserver_address:  *domain_adminserver_address
    weblogic_password:    *domain_wls_password   


user_instances:
  'testuser1':
    ensure:                 'present'
    password:               'weblogic1'
    authenticationprovider: 'DefaultAuthenticator'
    realm:                  'myrealm'
    description:            'my test user'
  'testuser2':
    ensure:                 'present'
    password:               'weblogic1'
    authenticationprovider: 'DefaultAuthenticator'
    realm:                  'myrealm'
    description:            'my test user'
  'testuser3':
    ensure:                 'present'
    password:               'weblogic1'
    authenticationprovider: 'DefaultAuthenticator'
    realm:                  'myrealm'
    description:            'my test user'

group_instances:
  'TestGroup':
    ensure:                 'present'
    authenticationprovider: 'DefaultAuthenticator'
    description:            'My TestGroup'
    realm:                  'myrealm'
    users:
      - 'testuser1'
      - 'testuser2'
    require:
      - Wls_user[testuser1]
      - Wls_user[testuser2]
  'SuperUsers':
    ensure:                 'present'
    authenticationprovider: 'DefaultAuthenticator'
    description:            'SuperUsers'
    realm:                  'myrealm'
    users:
      - 'testuser2'
    require:                Wls_user[testuser2]


# create 2 machines
machines_instances:
  'Node1':
    ensure:         'present'
    listenaddress:  '127.0.0.1'
    listenport:     '5556'
    machinetype:    'UnixMachine'
    nmtype:         'SSL'

server_vm_args_permsize:      &server_vm_args_permsize     '-XX:PermSize=256m'
server_vm_args_max_permsize:  &server_vm_args_max_permsize '-XX:MaxPermSize=256m'
server_vm_args_memory:        &server_vm_args_memory       '-Xms752m'
server_vm_args_max_memory:    &server_vm_args_max_memory   '-Xmx752m'


server_instances:
  'wlsServer1':
    ensure:                                'present'
    arguments:
           - *server_vm_args_permsize
           - *server_vm_args_max_permsize
           - *server_vm_args_memory
           - *server_vm_args_max_memory
           - '-Dweblogic.Stdout=/var/log/weblogic/wlsServer1.out'
           - '-Dweblogic.Stderr=/var/log/weblogic/wlsServer1_err.out'
    # listenaddress:                         '127.0.0.1'
    listenport:                            '8001'
    logfilename:                           '/var/log/weblogic/wlsServer1.log'
    machine:                               'Node1'
    sslenabled:                            '1'
    ssllistenport:                         '8201'
    sslhostnameverificationignored:        '1'
    jsseenabled:                           '1'
    require:                               Wls_machine[Node1]

cluster_instances:
  'WebCluster':
    ensure:                     'present'
    migrationbasis:             'consensus'
    servers:
      - 'wlsServer1'
    messagingmode:              'unicast'
    require:
      - Wls_server[wlsServer1]

file_persistence_folders:
   '/opt/oracle/wlsdomains/domains/Wls1221/persistence1':
      ensure:     directory
      recurse:    false
      replace:    false
      mode:       '0775'
      owner:      'oracle'
      group:      'dba'

file_persistence_store_instances:
  'jmsFile1':
    ensure:         'present'
    directory:      'persistence1'
    target:
      - 'wlsServer1'
    targettype:
      - 'Server'
    require:
      - Wls_server[wlsServer1]
      - File[/opt/oracle/wlsdomains/domains/Wls1221/persistence1]


jmsserver_instances:
  'jmsServer1':
     ensure:              'present'
     target:
       - 'wlsServer1'
     targettype:
       - 'Server'
     persistentstore:     'jmsFile1'
     persistentstoretype: 'FileStore'
     require:
       - Wls_server[wlsServer1]
       - Wls_file_persistence_store[jmsFile1]

jms_module_instances:
   'jmsClusterModule':
     ensure:      'present'
     target:
       - 'WebCluster'
     targettype:
       - 'Cluster'
     require:     Wls_cluster[WebCluster]

jms_subdeployment_instances:
   'jmsClusterModule:jmsServers':
      ensure:     'present'
      target:
        - 'jmsServer1'
      targettype:
        - 'JMSServer'
      require:
        - Wls_jms_module[jmsClusterModule]
        - Wls_jmsserver[jmsServer1]
   'jmsClusterModule:wlsServers':
      ensure:     'present'
      target:
        - 'WebCluster'
      targettype:
        - 'Cluster'
      require:
        - Wls_jms_module[jmsClusterModule]
        - Wls_cluster[WebCluster]

jms_connection_factory_instances:
  'jmsClusterModule:cf':
    ensure:             'present'
    jmsmodule:          'jmsClusterModule'
    defaulttargeting:   '0'
    jndiname:           'jms/cf'
    subdeployment:      'wlsServers'
    transactiontimeout: '3600'
    xaenabled:          '0'
    require:
      - Wls_jms_module[jmsClusterModule]
      - Wls_jms_subdeployment[jmsClusterModule:wlsServers]
  'jmsClusterModule:cf2':
    ensure:             'present'
    jmsmodule:          'jmsClusterModule'
    defaulttargeting:   '1'
    jndiname:           'jms/cf2'
    transactiontimeout: '3600'
    xaenabled:          '1'
    require:            Wls_jms_module[jmsClusterModule]

jms_queue_instances:
   'jmsClusterModule:ErrorQueue':
     ensure:                   'present'
     distributed:              '1'
     expirationpolicy:         'Discard'
     jndiname:                 'jms/ErrorQueue'
     redeliverydelay:          '-1'
     redeliverylimit:          '-1'
     subdeployment:            'jmsServers'
     defaulttargeting:         '0'
     timetodeliver:            '-1'
     timetolive:               '-1'
     require:
       - Wls_jms_module[jmsClusterModule]
       - Wls_jms_subdeployment[jmsClusterModule:jmsServers]
   'jmsClusterModule:Queue1':
     ensure:                   'present'
     distributed:              '1'
     errordestination:         'ErrorQueue'
     expirationpolicy:         'Redirect'
     jndiname:                 'jms/Queue1'
     redeliverydelay:          '2000'
     redeliverylimit:          '3'
     subdeployment:            'jmsServers'
     defaulttargeting:         '0'
     timetodeliver:            '-1'
     timetolive:               '300000'
     require:
       - Wls_jms_module[jmsClusterModule]
       - Wls_jms_subdeployment[jmsClusterModule:jmsServers]
       - Wls_jms_queue[jmsClusterModule:ErrorQueue]
   'jmsClusterModule:Queue2':
     ensure:                   'present'
     distributed:              '1'
     expirationloggingpolicy:  '%header%%properties%'
     expirationpolicy:         'Log'
     jndiname:                 'jms/Queue2'
     redeliverydelay:          '2000'
     redeliverylimit:          '3'
     subdeployment:            'jmsServers'
     defaulttargeting:         '0'
     timetodeliver:            '-1'
     timetolive:               '300000'
     require:
       - Wls_jms_module[jmsClusterModule]
       - Wls_jms_subdeployment[jmsClusterModule:jmsServers]


jms_topic_instances:
   'jmsClusterModule:Topic1':
     ensure:            'present'
     defaulttargeting:  '0'
     distributed:       '1'
     expirationpolicy:  'Discard'
     jndiname:          'jms/Topic1'
     redeliverydelay:   '2000'
     redeliverylimit:   '2'
     subdeployment:     'jmsServers'
     timetodeliver:     '-1'
     timetolive:        '300000'
     require:
       - Wls_jms_module[jmsClusterModule]
       - Wls_jms_subdeployment[jmsClusterModule:jmsServers]


